<?php

return [

    'title' => [
        'senior',
        'sénior',
        'tech lead',
        'confirmé',
        'commercial',
        "Copywriter",
        "Talent Acquisition Specialist",
        "Business Developer",
        "Chef de projet",
        "Acheteur",
        "Account Manager",
        "Architecte",
        "communication digitale",
        "Key Account Manager",
        "Technical Leader",
        "Product Owner",
        "CTO",
        "Lead Développeur",
        "Web Designer",
        "lead",
        "Expérimenté",
        "Chef de produit",
        "Designer",
        "graphiste",
        "electrique",
        "recrutement",
        "Traffic Manager",
        "Conseiller financier",
        "Traffic Manager",
        "Chargé d'Acquisition",
        "Directeur Artistique ",
        "Auditeur junior",
        "Product Manager",
        "Marketing Digital",
        "Présence management",
        "Responsable Communication",
        "E-Store Manager",
        "Assistant Marketing",
        "SEA",
        "DEVOPS AWS",

        "BIG DATA",
        "Ingénieur Cloud",
        "Formateur",

        "Développeur foncier",
        "Consultant Junior",
        "Content Marketing Junior",
        "E-merchandising",
        "Risk Consulting",
        "Assistant(e) de direction/communication",
        "DÉVELOPPEUR PANORAMA",
        "Consultant(e) Social Média",
        "Experimente",
        "Ingénieur QA",
        "Expert technique",
        "Responsable Digital Content",
        "Community Manager Junior",
        "Assistant Marketing",
        "Chargé(e) de partenariats",
        "webredacteur",
        "Administrateur Applicatif",
        "Ingénieur Système",
        "Web Analyst",
        "Chargé(e) de projet marketing",
        "charge d’acquisition",
        "consultant erp",
        "devops",
    ],

    'description' => [
        "PMO Junior",
        "Junior Communications",
        "Consultant Sécurité",
        "Incidentologie",
        "Chef​ de​ projet​ fonctionnel​",
        "chargé d'affaires",
        "idéalement 2 ans",
        "idéalement 3 ans",
        "idéalement 4 ans",
        "idéalement 5 ans",
        "au minimum 2 ans d'expérience",
        "au minimum 3 ans d'expérience",
        "au minimum 4 ans d'expérience",
        "au minimum 5 ans d'expérience",
        "expérience d'au moins 2 ans",
        "expérience d'au moins 3 ans",
        "expérience d'au moins 4 ans",
        "expérience d'au moins 5 ans",
        "Au moins 2 ans d'experience",
        "Au moins 3 ans d'experience",
        "Au moins 4 ans d'experience",
        "Au moins 5 ans d'experience",
        "Au moins 2 ans d'expérience",
        "Au moins 3 ans d'expérience",
        "Au moins 4 ans d'expérience",
        "Au moins 5 ans d'experience",
        "2 ans minimum d’expérience",
        "3 ans minimum d’expérience",
        "4 ans minimum d’expérience",
        "5 ans minimum d’expérience",
        "2 ans d’expérience",
        "3 ans d’expérience",
        "4 ans d’expérience",
        "5 ans d’expérience",
        "vous justifiez d'une expérience de 2 ans",
        "vous justifiez d'une expérience de 3 ans",
        "vous justifiez d'une expérience de 4 ans",
        "vous justifiez d'une expérience de 5 ans",
        "vous justifiez d'au moins 2 ans d'expérience",
        "vous justifiez d'au moins 3 ans d'expérience",
        "vous justifiez d'au moins 4 ans d'expérience",
        "vous justifiez d'au moins 5 ans d'expérience",
        "plus de 2 ans d'expérience",
        "plus de 3 ans d'expérience",
        "plus de 4 ans d'expérience",
        "plus de 5 ans d'expérience",
        "idéalement 2 à 3 ans",
        "idéalement 3 à 4 ans",
        "idéalement 4 à 5 ans",

        "d’une expérience d’au moins 2 ans",
        "d’une expérience d’au moins 3 ans",
        "d’une expérience d’au moins 4 ans",
        "d’une expérience d’au moins 5 ans",

        "vous justifiez d'au moins 2",
        "vous justifiez d'au moins 3",
        "vous justifiez d'au moins 4",
        "vous justifiez d'au moins 5",
        "vous justifiez d'au moins de deux",
        "vous justifiez d'au moins de trois",
        "vous justifiez d'au moins de quatre"
        // auto didacte ou jeu diplomé a mettre en highlight

    ]
];
